controller_manager:
  ros__parameters:
    update_rate: 500
    use_sim_time: true
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
joint_state_broadcaster:
  ros__parameters:
    publish_rate: 500.0
effort_controller:
  ros__parameters:
    state_publish_rate: 500.0
    action_monitor_rate: 500.0
    joints:
      - 2-FL-HFE
      - 3-FL-KFE
      - 4-FR-HAA
      - 1-FL-HAA
      - 8-HR-HFE
      - 9-HR-KFE   
      - 6-FR-KFE
      - 7-HR-HAA
      - 10-HL-HAA
      - 5-FR-HFE
      - 11-HL-HFE
      - 12-HL-KFE

    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - velocity
      - position

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

